Description: >-
  Upload an object to an S3 bucket, triggering a Lambda event, returning the
  object key as a Stack Output. AWS Spam Filter.
Parameters:
  MyLambdaEnvName:
    Type: Aws::SSM::id::Value<String>
    Default: sms-spam-classifier-ll-2020-05-07-07-24-58-952 
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    DependsOn: BucketPermission
    Properties:
      BucketName: emailstoragehw4-cloudformation
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:*'
            Function: !GetAtt S3ObjectFunction.Arn
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: Bucket
    Properties: 
      Bucket: emailstoragehw4-cloudformation
      PolicyDocument:
        Statement:
        - Sid: AllowSESPuts
          Effect: Allow
          Principal:
            Service: ses.amazonaws.com
          Action: s3:PutObject
          Resource: arn:aws:s3:::emailstoragehw4-cloudformation/*
          Condition:
            StringEquals:
              aws:Referer: '482781774333'
  BucketPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref S3ObjectFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: arn:aws:s3:::emailstoragehw4-cloudformation
  S3ObjectFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: S3 Object Custom Resource
      Handler: lambda_function.lambda_handler
      Role: 'arn:aws:iam::482781774333:role/service-role/S3Trigger-role-x6ke87lq'
      FunctionName: S3Trigger-cloudformation
      Layers: 
       - arn:aws:lambda:us-east-1:113088814899:layer:Klayers-python37-pandas:1
      Code:
        S3Bucket: spamham
        S3Key: S3Trigger-64953803-85cc-4076-b51a-d3d50915a45f.zip
      Environment:
        Variables:
          id: !Ref MyLambdaEnvName
      Timeout: 60
      Runtime: python3.7
  ReceiptRule1:
    Type: AWS::SES::ReceiptRule
    DependsOn: Bucket
    Properties:
      RuleSetName: stackruleset
      Rule:
        Name: myrule
        Enabled: true
        ScanEnabled: false
        Recipients: 
          - rajuttam@mailfiltering.tech
        Actions:
          - S3Action:
              BucketName: emailstoragehw4-cloudformation